
SELECT SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) "DOMAIN"
     , COUNT(NVL(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1),1)) "EA"
     , SUM(COUNT(NVL(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1),1))) OVER() "SUM_DOMAIN"
     , COUNT(NVL(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1),1))/
       SUM(COUNT(NVL(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1),1))) OVER() * 100 "%"
  FROM PROFESSOR
 GROUP BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)
 ORDER BY 1;
