SELECT SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) "DOMAIN"
     , COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)) "EA"
     , SUM(COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1))) OVER() "SUM_DOMAIN"
     , COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1))/
       SUM(COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1))) OVER() * 100 "%"
  FROM PROFESSOR
 GROUP BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)
 ORDER BY 1;
